galeria/urls.py
from django.urls import path
from . import views
from .views import GaleriaListView, galeria_detalle, UltimasImagenes, CustomLoginView

app_name = 'galeria'

urlpatterns = [
    path('', GaleriaListView.as_view(), name='galeria_list'),
    path('cargar/login/', CustomLoginView.as_view(), name='login'),
    path('cargar/', views.fileupload, name='cargar_imagenes'),
    path('<slug:slug>/', galeria_detalle, name='galeria_detalle'),
    path('api/<slug:slug_sitio>/', UltimasImagenes.as_view(), name='ultimas_imagenes'),




    # path('cargar/<int:pk>/', views.cargar_imagenes, name='cargar_imagenes'),
    # path('galeria/<int:pk>/cargar/', views.cargar_imagenes, name='cargar_imagenes'),
    # Añade más rutas según necesites
]

main/urls.py
from django.urls import path
from . import views
from .views import buscar_sitio

urlpatterns = [
    path('', views.Home.as_view(), name='Home'),
    path('buscar_sitio/', buscar_sitio, name='buscar_sitio'),
]

galeria/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from main.models import Sitio
from django.conf import settings
 # Importa el modelo User

class Galeria(models.Model):
    sitio = models.OneToOneField(Sitio, on_delete=models.CASCADE, editable=False)
    entel_id = models.CharField(max_length=10, editable=False)
    nombre = models.CharField(max_length=100, blank=True)
    descripcion = models.TextField(blank=True)
    slug = models.SlugField(max_length=10, unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.sitio)[:10]
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.sitio}_{self.entel_id} - {self.nombre} "
        
class Imagen(models.Model):
    galeria = models.ForeignKey(Galeria, on_delete=models.CASCADE, related_name='imagenes')
    imagen = models.ImageField(upload_to='imagenes/')
    descripcion = models.CharField(max_length=52, blank=True, null=True) 
    fecha_carga = models.DateField(default=timezone.now)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='imagenes_subidas')

    def __str__(self):
        return f"{self.galeria.sitio} - {self.fecha_carga}"


class Comentario(models.Model):
    galeria = models.ForeignKey(Galeria, on_delete=models.CASCADE, related_name='comentario')
    comentario = models.TextField(blank=True, null=True)
    fecha_carga = models.DateField(default=timezone.now)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comentarios_subidas')

    def __str__(self):
        return f"{self.galeria.sitio} - {self.comentario}"

galeria/forms.py
from django import forms
from .models import Galeria, Imagen, Comentario
from django.utils import timezone

class ImagesForm(forms.ModelForm):
        # Aquí agregas un campo extra para el comentario, este no está vinculado directamente a un modelo
    comentario = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Imagen
        fields = ['galeria', 'fecha_carga', 'comentario']

    def __init__(self, *args, **kwargs):
        super(ImagesForm, self).__init__(*args, **kwargs)
        self.fields['fecha_carga'].widget = forms.DateInput(attrs={
            'class': 'datepicker',
            'type': 'text',
        })
        self.fields['fecha_carga'].initial = timezone.now().date()

galeria/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Max
from django.views.generic import ListView
from .forms import ImagesForm
from .models import Galeria, Imagen, Comentario
from django.contrib import messages
from django.db.models import DateField
from django.db.models.functions import Trunc
from collections import OrderedDict
from rest_framework.views import APIView
from django.shortcuts import get_object_or_404
from .serializers import GaleriaSerializer
from rest_framework.response import Response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

class GaleriaListView(ListView):
    model = Galeria
    template_name = 'galeria_list.html'
    context_object_name = 'galerias'

    def get_queryset(self):
        queryset = super().get_queryset().annotate(ultima_fecha_imagen=Max('imagenes__fecha_carga')).prefetch_related('imagenes')
        for galeria in queryset:
            ultima_imagen = galeria.imagenes.filter(fecha_carga=galeria.ultima_fecha_imagen).first()
            galeria.ultima_imagen = ultima_imagen
        return queryset


# @login_required  # Asegura que solo usuarios logueados puedan acceder a esta vista


@login_required(login_url='login/')
def fileupload(request):
    if request.method == 'POST':
        form = ImagesForm(request.POST, request.FILES)
        if form.is_valid():
            galeria = form.cleaned_data['galeria']
            fecha_carga = form.cleaned_data['fecha_carga']
            comentario_texto = form.cleaned_data.get('comentario') 
            images = request.FILES.getlist('images')  # Asegúrate de que el nombre del campo en el formulario HTML sea 'images'

            imagenes_a_crear = [Imagen(imagen=image, galeria=galeria, fecha_carga=fecha_carga, usuario=request.user) for image in images]

            # Usar bulk_create para mejorar la eficiencia
            Imagen.objects.bulk_create(imagenes_a_crear)

            # Crear y guardar el comentario si existe alguno
            if comentario_texto:  # Verificar si hay algún comentario para guardar
                Comentario.objects.create(galeria=galeria, comentario=comentario_texto, fecha_carga=fecha_carga, usuario=request.user)

            # Añadir un mensaje de éxito
            messages.success(request, "Imágenes cargadas correctamente.")

            return redirect('galeria:galeria_list')
        else:
            messages.error(request, "Se encontraron errores en el formulario, por favor corrígelos.")
            return render(request, "cargar.html", {'form': form})
    else:
        form = ImagesForm()
    
    context = {'form': form}
    return render(request, "cargar.html", context)

def galeria_detalle(request, slug):
    galeria = get_object_or_404(Galeria, slug=slug)
    
    # Obtener imágenes y truncar la fecha
    imagenes = Imagen.objects.filter(galeria=galeria).annotate(fecha=Trunc('fecha_carga', 'day', output_field=DateField())).order_by('-fecha')
    
    # Obtener comentarios y truncar la fecha
    comentarios = Comentario.objects.filter(galeria=galeria).annotate(fecha=Trunc('fecha_carga', 'day', output_field=DateField())).order_by('-fecha')
    
    items_por_fecha = OrderedDict()
    
    # Combinar imágenes y comentarios en la misma estructura
    for item in list(imagenes) + list(comentarios):
        items_por_fecha.setdefault(item.fecha, {'imagenes': [], 'comentarios': []})
        if isinstance(item, Imagen):
            items_por_fecha[item.fecha]['imagenes'].append(item)
        elif isinstance(item, Comentario):
            items_por_fecha[item.fecha]['comentarios'].append(item)

    context = {
        'galeria': galeria,
        'items_por_fecha': items_por_fecha,
    }
    return render(request, 'galeria_detalle.html', context)

class CustomLoginView(LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True  # Redirige a los usuarios ya autenticados
    next_page = reverse_lazy('imgs/cargar') 


class UltimasImagenes(APIView):
    def get(self, request, slug_sitio):
        galeria = get_object_or_404(Galeria, slug=slug_sitio)
        serializer = GaleriaSerializer(galeria, context={'request': request})
        return Response(serializer.data)

galeria/templates/cargar.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <!-- Incluir JavaScript de Flatpickr -->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

{% endblock css %}

{% block content %} 
  <div class="w-full max-w-7xl mx-auto px-4 py-6">
    <!-- Título del formulario -->
    <div class="text-center mb-8">
      <h1 class="text-2xl font-bold text-gray-800">CARGA DE IMAGENES</h1>
      <p class="text-md text-gray-500">Escoge el sitio para la carga de multiples imagenes.</p>
    </div>

    <form method="post" enctype="multipart/form-data" class="space-y-4 bg-white p-6 rounded-lg shadow-lg">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-4">
                <label for="{{ field.id_for_label }}" class="block text-sm font-medium text-gray-700">{{ field.label }}</label>
                {{ field|add_class:"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" }}
                {% if field.help_text %}
                    <p class="mt-2 text-sm text-gray-500">{{ field.help_text }}</p>
                {% endif %}
                {% for error in field.errors %}
                    <p class="text-sm text-red-600">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
            <input type="file" name="images" multiple class="form-control">
            <div>
                <button type="submit" class="px-4 py-2 mt-2 bg-blue-500 text-white rounded hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50">
                Cargar imagenes
            </div>
        </button>
    </form>
  </div>

{% endblock content %} 

{% block extra_js %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            flatpickr('.datepicker', {
                dateFormat: "d/m/Y",
            });
        });
    </script>
{% endblock extra_js %}

galeria/templates/galeria_detalle.html
<!-- galeria_detalle.html -->
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center text-3xl font-bold text-gray-800 mb-1">{{ galeria.sitio }}_{{ galeria.entel_id }} </h1>
<p class="text-center text-2xl text-gray-600 ">{{ galeria.nombre }} {{ galeria.descripcion }}</p>
      
{% for fecha, items in items_por_fecha.items %}
    {% with day=fecha|date:"l" %}
    <h2 class="{% if day == "sábado" or day == "domingo" %}text-red-500{% else %}text-gray-700{% endif %} text-xl font-semibold mb-0 ml-1">
        {{ fecha|date:"j F Y (l)" }}
    </h2>
    {% endwith %}
    
    <!-- Mostrar imágenes de ese día -->
    <div class="columns-3 gap-4 my-3 mx-2">    
    {% for imagen in items.imagenes %}
        <img class="h-auto max-w-full rounded-lg my-3" src="{{ imagen.imagen.url }}" alt="{{ imagen.descripcion }}" >
    {% endfor %}

    <!-- Verificar y Mostrar comentarios de ese día si existen -->
    {% if items.comentarios %}   
        {% for comentario in items.comentarios %}
        <div class="bg-yellow-200 w-full min-h-14 flex flex-col justify-between rounded-lg p-4">
            <p class="mb-4">{{ comentario.comentario }}</p>
            <div class="text-right text-sm text-gray-600">
                {{ comentario.usuario }}
            </div>
        </div>       
        {% endfor %}
    {% endif %}

    </div>
    

{% endfor %}

{% endblock content %}

galeria/templates/galeria_list.html
{% extends 'base.html' %}

{% block body_class %}bg-slate-400{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="text-red-600 {{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class=" container mx-auto px-4 py-8">
    <div class="grid md:grid-cols-3 sm:grid-cols-2 gap-4">
        {% for galeria in galerias %}
            <a href="{% url 'galeria:galeria_detalle' slug=galeria.slug %}">
                <div class="bg-white rounded-lg shadow-md overflow-hidden">
                    {% if galeria.ultima_imagen %}
                        <img src="{{ galeria.ultima_imagen.imagen.url }}" alt="Imagen destacada" class="w-full h-48 object-cover">
                        {{ galeria.ultima_imagen.fecha_carga|date:"d/m/Y" }}
                    {% else %}
                        <div class="w-full h-48 bg-gray-200 flex items-center justify-center">
                            <span>No hay imagen disponible</span>
                        </div>
                    {% endif %}
                    <div class="px-4">
                        <h2 class="text-lg font-bold text-gray-900">{{ galeria.sitio }}_{{ galeria.entel_id }}</h2>
                        <p class="text-gray-700">{{ galeria.nombre }} {{ galeria.descripcion|truncatewords:20 }}</p>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
</div>

<!-- Botón Ir a Cargar, colocado en la parte superior derecha -->
{% if user.is_authenticated %}
<div class="absolute top-0 right-0 m-4">
    <a href="{% url 'galeria:cargar_imagenes' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Cargar Imagenes
    </a>
</div>
{% endif %}
{% endblock content %}

galeria/templates/login.html
{% extends "base.html" %}  <!-- Asegúrate de extender tu base.html o cualquier base que uses -->

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <div>
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                Inicia sesión en tu cuenta
            </h2>
        </div>
        <form class="mt-8 space-y-6" action="#" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            <div class="rounded-md shadow-sm -space-y-px">
                <div>
                    <label for="{{ form.username.id_for_label }}" class="block text-sm font-medium text-gray-700">Usuario</label>
                    <input id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" type="text" autocomplete="username" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Tu usuario">
                </div>
                <div>
                    <label for="{{ form.password.id_for_label }}" class="block text-sm font-medium text-gray-700">Contraseña</label>
                    <input id="{{ form.password.id_for_label }}" name="{{ form.password.name }}" type="password" autocomplete="current-password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Tu contraseña">
                </div>
            </div>

            <div>
                <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Iniciar sesión
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}